# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3ZZcWP_Lph9YlaLRN7sLhXpXbe8udQb
"""

!pip install pandas openpyxl



from google.colab import drive
drive.mount('/content/drive')



import pandas as pd

# Ganti 'your_uploaded_file.xlsx' dengan nama file yang diunggah
file_path = 'maba2024.xlsx'
df = pd.read_excel(file_path)

# Mencari baris yang mengandung kata 'SUDAH' atau 'BELUM' di seluruh kolom
sudah_df = df[df.apply(lambda row: row.astype(str).str.contains('SUDAH', case=False).any(), axis=1)]
belum_df = df[df.apply(lambda row: row.astype(str).str.contains('BELUM', case=False).any(), axis=1)]

# Menyimpan data yang sudah dipisahkan ke file Excel baru
output_file = 'output_file.xlsx'
with pd.ExcelWriter(output_file) as writer:
    sudah_df.to_excel(writer, sheet_name='SUDAH', index=False)
    belum_df.to_excel(writer, sheet_name='BELUM', index=False)

print(f"Data telah dipisahkan dan disimpan ke file {output_file}")

from google.colab import files
files.download('output_file.xlsx')